name: learn-github-actions
run-name: ${{github.actor}} is learning Github Actions
on: [push]
jobs: 
    install-dependencies: 
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with: 
                go-version: '1.21.x'
            - name: Display Go version
              run: go version
            - name: Run unit tests
              run: go test ./...
            - name: Test with Go
              run: go test -json > TestResults.json
            - name: Upload Go test results
              uses: actions/upload-artifact@v4
              with:
                name: Go-results
                path: TestResults.json