name: run manually
run-name: ${{github.actor}} is learning Github Actions
on: 
    workflow_dispatch:
        inputs:
            logLevel:
                description: 'Log Level'
                required: true 
                type: choice
                options:
                    - info
                    - warning
                    - debug
            dry-run:
                description: 'Test scenario'
                required: false
                type: boolean
            environment:
                description: 'Environment to run tests against'
                type: choice
                required: true
                options: 
                    - dev
                    - qa
                    - stage 
                
jobs:
    log-the-inputs:
        runs-on: ubuntu-latest
        steps:
        - if: ${{ inputs.dry-run }} 
          id: dry-run
          run: echo "VAR1=SISENIOR" >> "$GITHUB_OUTPUT"
          env: 
            VAR1: SISENIOR
        - run: echo ${{ steps.dry-run.outputs.VAR1 }}
        - run: |
            echo "LEVEL: ${{ inputs.logLevel }}"
            echo "DRY-RUN: ${{ inputs.dry-run }}"
            echo "ENVIRONMENT: ${{ inputs.environment }}"
            echo "NO: $NO"
          env: 
            NO: 123